services:
  postgres:
    image: docker.io/postgres:17.4-alpine3.21
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      - 'POSTGRES_DATABASE=${DATABASE_NAME}'
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: