$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  src:
    - 'src/**/*'
    - 'package.json'
    - 'tsconfig.json'
    - '/tsconfig.options.json'
  tests:
    - 'tests/**/*'
    - 'tsconfig.spec.json'
    - '**/*.spec.ts'

tasks:
  dev:
    command: 'bun --watch src/main.ts server:start'
    local: true

  start:
    command: 'bun run dist/main.js'
    deps:
      - 'build'

  #  build:
  #    command:
  #     - 'bun'
  #     - 'build'
  #     - '--compile'
  #     - '--target=bun-linux-x64-modern'
  #     - 'src/main.ts'
  #     - '--outfile main'
  #    values:
  #      - '@group(src)'

  test:
    command: 'bun test'
    inputs:
      - '@group(src)'
      - '@group(tests)'

  build:
    command: 'bun build.ts'
    inputs:
      - 'build.ts'
      - '@group(src)'

  publish:
    command: 'docker buildx build --cache-from=type=gha --cache-to=type=gha,mode=max -f Dockerfile --tag ghcr.io/${$vcsRepository%%/*}/$project:$vcsRevision .'
    env:
      DOCKER_BUILDKIT: '1'
    inputs:
      - '$GITHUB_REPOSITORY'
    deps:
      - 'build'
      - 'test'

  typecheck:
    command:
      - 'tsc'
      - '--build'
      - '--pretty'
      - '--verbose'
    inputs:
      - '@group(src)'
      - '@group(tests)'
    outputs:
      - 'lib'